### ISSUE TITLE
[FEAT] iOS 세미나 1주차 실습 및 학습 정리

### ISSUE THREAD

**Issue by ningpop** [29th-WE-SOPT-iOS-Part/LeeNamJoon#1]
학습 정리 페이지는 [Here](https://ningpop.notion.site/1-0f184db1e89f4359a53ebb53fcca7b11)

## 📝 To-do

▶️ iOS 기초
- [x] Cocoa Touch Framework
- [x] Life Cycle(생명주기)
- [x] 앱의 상태(App State) 변화
- [x] App Life-Cycle
- [x] AppDelegate.swift
- [x] ViewController
- [x] 뷰의 상태 변화 감지 메서드

▶️ Xcode 사용하기
- [x] Xcode란?
- [x] 프로젝트 생성
- [x] 프로젝트 살펴보기
- [x] 파일 살펴보기

▶️ UI 구성하기
- [x] 라벨, 버튼 생성 실습
- [x] @IBOutlet과 @IBAction

▶️ 화면 전환
- [x] 모달(Modal)
- [x] 세그웨이(Segue)로 모달 구현하기
- [x] 코드로 모달 구현하기
- [x] 네비게이션(Navigation)
- [x] Navigation Controller와 Navigation Stack

▶️ 데이터 전달 기초
- [x] ViewController를 상속받은 나의 ViewController끼리의 데이터 전달 실습
