### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by ningpop** [29th-WE-SOPT-iOS-Part/LeeNamJoon#12]
## 📌  Feature Issue

TableView와 CollectionView를 활용하여 Youtube 홈 화면 구성하기

## 📝  To-do

▶️ UI 구성하기
- [x] Xib로 TableView Cell 만들고 AutoLayout 적용
- [x] CollectionView Cell 만들고 AutoLayout 적용

▶️ 도전과제
- [ ] 실제 유튜브의 필터링 셀도 만들어보기
