### ISSUE TITLE
[FEAT] iOS 세미나 7주차 실습 및 학습 정리

### ISSUE THREAD

**Issue by ningpop** [29th-WE-SOPT-iOS-Part/LeeNamJoon#18]
학습 정리 페이지는 [Here](https://ningpop.notion.site/7-58d599eb18be48e7a2ff6b0acaadb25d)

## 📝  To-do

▶️ 데이터 전달 심화 - View Controller 간
- [x] present / push시에 프로퍼티에 접근해 넘겨주는 방식
- [x] Segue를 활용해서 데이터를 넘겨주는 방식
- [x] NotificationCenter를 활용해 데이터를 넘기는 방식

▶️ 데이터 전달 심화 - View 계층 간
- [x] Protocol / Delegation을 활용해서 데이터를 넘겨받는 방식
- [x] Closure를 활용해서 데이터를 넘겨받는 방식

▶️ UIGestureRecognizer
- [x] UIGestureRecognizer
- [x] 인터페이스 빌더를 통해 추가하기
- [x] 코드로 추가하기
