### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by ningpop** [29th-WE-SOPT-iOS-Part/LeeNamJoon#20]
## 📌  Feature Issue

데이터 연결 심화, UIGestureRecognizer

## 📝  To-do

- [x] imageView에 tap gesture recognizer를 달아서 action 보여주기
- [x] action과 함께 화면전환하기
- [x] 버튼 누르면 이전화면으로 dismiss하기
